serenade.global().pronounce("'cause","because")
serenade.global().pronounce("'twas","it was")
serenade.global().pronounce("a'ight","alright")
serenade.global().pronounce("ain't","am not")
serenade.global().pronounce("amn't","am not")
serenade.global().pronounce("arencha","are not you")
serenade.global().pronounce("aren't ","are not")
serenade.global().pronounce("'bout","about")
serenade.global().pronounce("can't","cannot")
serenade.global().pronounce("cap'n","captain")
serenade.global().pronounce("'cause","because")
serenade.global().pronounce("'cept","except")
serenade.global().pronounce("c'mon","come on")
serenade.global().pronounce("could've","could have")
serenade.global().pronounce("couldn't","could not")
serenade.global().pronounce("couldn't've","could not have")
serenade.global().pronounce("cuppa","cup of")
serenade.global().pronounce("cuz","because")
serenade.global().pronounce("daren't","dare not")
serenade.global().pronounce("daresn't","dare not")
serenade.global().pronounce("dasn't","dare not")
serenade.global().pronounce("didn't","did not")
serenade.global().pronounce("doesn't","do not")
serenade.global().pronounce("don't","do not")
serenade.global().pronounce("dunno","do not know")
serenade.global().pronounce("d'ye","do you")
serenade.global().pronounce("d'ya","do you")
serenade.global().pronounce("e'en","even")
serenade.global().pronounce("e'er","ever")
serenade.global().pronounce("'em","them")
serenade.global().pronounce("everybody's","everybody has")
serenade.global().pronounce("everyone's","everyone is")
serenade.global().pronounce("everything's","everything is")
serenade.global().pronounce("finna","fixing to")
serenade.global().pronounce("'gainst","against")
serenade.global().pronounce("g'day","good day")
serenade.global().pronounce("gimme"," give me")
serenade.global().pronounce("giv'n","given")
serenade.global().pronounce("gi'z","give us")
serenade.global().pronounce("gonna","going to")
serenade.global().pronounce("gon't","go not")
serenade.global().pronounce("gotta","get to")
serenade.global().pronounce("hadn't","had not")
serenade.global().pronounce("had've","had have")
serenade.global().pronounce("hasn't","has not")
serenade.global().pronounce("haven't","have not")
serenade.global().pronounce("he'd'nt've","he would not have")
serenade.global().pronounce("he'd","he would")
serenade.global().pronounce("he'll","he will")
serenade.global().pronounce("helluva","hell of a")
serenade.global().pronounce("he's","he is")
serenade.global().pronounce("here's","here is")
serenade.global().pronounce("how'd","how did")
serenade.global().pronounce("how'll","how will")
serenade.global().pronounce("howdy","how do you do")
serenade.global().pronounce("how'll","how will")
serenade.global().pronounce("how're","how are")
serenade.global().pronounce("how's","how is")
serenade.global().pronounce("i'am","I am")
serenade.global().pronounce("i'd","I had")
serenade.global().pronounce("i'll","I will")
serenade.global().pronounce("i'm","I am")
serenade.global().pronounce("i'm'onna","I am going to")
serenade.global().pronounce("imma","I am about to")
serenade.global().pronounce("i'm'onna","I am going to")
serenade.global().pronounce("i'm'na","I am going to")
serenade.global().pronounce("innit","is not it")
serenade.global().pronounce("i've","I have")
serenade.global().pronounce("isn't","is not")
serenade.global().pronounce("it'd","it would")
serenade.global().pronounce("it'll","it will")
serenade.global().pronounce("it's","it is")
serenade.global().pronounce("Idunno","do not know")
serenade.global().pronounce("kinda","kind of")
serenade.global().pronounce("lemme","let me")
serenade.global().pronounce("loven't","love not")
serenade.global().pronounce("let's","let us")
serenade.global().pronounce("ma'am","madam")
serenade.global().pronounce("mayn't","may not")
serenade.global().pronounce("may've","may have")
serenade.global().pronounce("might've","might have")
serenade.global().pronounce("mightn't","might not")
serenade.global().pronounce("mine's","mine is")
serenade.global().pronounce("must've","must have")
serenade.global().pronounce("mustn't","must not")
serenade.global().pronounce("mustn't've","must not have")
serenade.global().pronounce("'neath","beneath")
serenade.global().pronounce("needn't","need not")
serenade.global().pronounce("nall","not all")
serenade.global().pronounce("ne'er","never")
serenade.global().pronounce("nothing's","nothing is")
serenade.global().pronounce("o'clock","of the clock")
serenade.global().pronounce("o'er","over")
serenade.global().pronounce("ol'","old")
serenade.global().pronounce("ought'nt","ought not")
serenade.global().pronounce("ought'n't","ought not have")
serenade.global().pronounce("ought've","ought have")
serenade.global().pronounce("'round","around")
serenade.global().pronounce("shalln't","shall not")
serenade.global().pronounce("shan'","shall not")
serenade.global().pronounce("shan't","shall not")
serenade.global().pronounce("she'd","she had")
serenade.global().pronounce("she'll","she will")
serenade.global().pronounce("she's","she is")
serenade.global().pronounce("should've","should have")
serenade.global().pronounce("shouldn't","should not")
serenade.global().pronounce("shouldn't've"," should not have")
serenade.global().pronounce("somebody's","somebody is")
serenade.global().pronounce("someone's","someone is")
serenade.global().pronounce("something's","something is")
serenade.global().pronounce("so're","so are")
serenade.global().pronounce("so's","so is")
serenade.global().pronounce("so've","so have")
serenade.global().pronounce("that'd","that would")
serenade.global().pronounce("that'll","that will")
serenade.global().pronounce("that're","that are")
serenade.global().pronounce("that's","that is")
serenade.global().pronounce("there'd","there had")
serenade.global().pronounce("there'll","there will")
serenade.global().pronounce("there's","there has")
serenade.global().pronounce("these're","these are")
serenade.global().pronounce("these've","these have")
serenade.global().pronounce("they'd","they had")
serenade.global().pronounce("they'll","they will")
serenade.global().pronounce("they're","they are")
serenade.global().pronounce("they've","they have")
serenade.global().pronounce("this's","this is")
serenade.global().pronounce("those're","those are")
serenade.global().pronounce("those've","those have")
serenade.global().pronounce("'thout","without")
serenade.global().pronounce("'til","until")
serenade.global().pronounce("'tis","it is")
serenade.global().pronounce("to've","to have")
serenade.global().pronounce("tryna","trying to")
serenade.global().pronounce("'twas","it was")
serenade.global().pronounce("'tween","between")
serenade.global().pronounce("'tweren","it were")
serenade.global().pronounce("wasn't","was not")
serenade.global().pronounce("wanna"," want to've")
serenade.global().pronounce("wasn't","was not")
serenade.global().pronounce("w'all","we all")
serenade.global().pronounce("w'at","we at")
serenade.global().pronounce("we'd","we had")
serenade.global().pronounce("we'd've","we would have")
serenade.global().pronounce("we'll","we will")
serenade.global().pronounce("we're","we are")
serenade.global().pronounce("we've","we have")
serenade.global().pronounce("weren't","were not")
serenade.global().pronounce("what'd","what did")
serenade.global().pronounce("what'll","what will")
serenade.global().pronounce("what're","what are")
serenade.global().pronounce("what's","what is")
serenade.global().pronounce("what've","what have")
serenade.global().pronounce("where'd","where did")
serenade.global().pronounce("where're","where are")
serenade.global().pronounce("where's","where is")
serenade.global().pronounce("where've","where have")
serenade.global().pronounce("which'd","which did")
serenade.global().pronounce("which's","which has")
serenade.global().pronounce("which've","which have")
serenade.global().pronounce("who'd","who had")
serenade.global().pronounce("who'll","who will")
serenade.global().pronounce("who's","who is")
serenade.global().pronounce("who're","who are")
serenade.global().pronounce("who've","who have")
serenade.global().pronounce("why'd","why did")
serenade.global().pronounce("why'll","why will")
serenade.global().pronounce("why're","why are")
serenade.global().pronounce("why's","why is")
serenade.global().pronounce("won't","would not")
serenade.global().pronounce("wonnot","will not")
serenade.global().pronounce("would've","would have")
serenade.global().pronounce("wouldn't","would not")
serenade.global().pronounce("wouldn't've","would not have")
serenade.global().pronounce("y'aint","you are not")
serenade.global().pronounce("y'all","you all")
serenade.global().pronounce("y'all'dnt've","you all would not have")
serenade.global().pronounce("y'all're","you all are")
serenade.global().pronounce("y'knonwn","you know")
serenade.global().pronounce("yessir","yes sir")
serenade.global().pronounce("yes'nt","yes not")
serenade.global().pronounce("y'know","you know")
serenade.global().pronounce("you'd","you had")
serenade.global().pronounce("you'll","you will")
serenade.global().pronounce("you're","you are")
serenade.global().pronounce("you've","you have")
